package tests

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/farhapartex/coyote/contrib/migrate"
	"github.com/farhapartex/coyote/contrib/migrate/dialect"
	"github.com/farhapartex/coyote/core/db"
	"github.com/farhapartex/coyote/core/model"
	"github.com/farhapartex/coyote/core/settings"
	"gorm.io/gorm"
)

type widget struct {
	ID    string `gorm:"primaryKey;size:64"`
	Label string `gorm:"not null;size:120"`
}

type widgetV2 struct {
	ID       string `gorm:"primaryKey;size:64"`
	Label    string `gorm:"not null;size:120"`
	Quantity int
}

func (widgetV2) TableName() string { return "widgets" }

func newTestDB(t *testing.T) *gorm.DB {
	t.Helper()
	cfg := settings.Database{
		Alias:        "default",
		Engine:       settings.SQLite,
		Name:         filepath.Join(t.TempDir(), "test.db"),
		MaxOpenConns: 1,
	}
	handle, err := db.Open(cfg, db.Options{})
	if err != nil {
		t.Fatalf("opening database: %v", err)
	}
	t.Cleanup(func() { db.Close(handle) })
	return handle
}

func schemaFor(t *testing.T, handle *gorm.DB, entity any) *model.Schema {
	t.Helper()
	schema, err := model.Describe(handle, entity)
	if err != nil {
		t.Fatal(err)
	}
	return schema
}

func TestDiffCreatesMissingTable(t *testing.T) {
	handle := newTestDB(t)
	desired := migrate.SnapshotOf([]*model.Schema{schemaFor(t, handle, widget{})})

	change := migrate.Diff(migrate.Snapshot{}, desired)
	if change.Empty() {
		t.Fatal("a fresh snapshot should produce changes")
	}
	created, ok := change.Ops[0].(migrate.CreateTable)
	if !ok {
		t.Fatalf("first op = %T, want CreateTable", change.Ops[0])
	}
	if created.Table.Name != "widgets" {
		t.Errorf("table = %q", created.Table.Name)
	}
	if !strings.Contains(change.Ops[0].Describe(), "create table widgets") {
		t.Errorf("describe = %q", change.Ops[0].Describe())
	}
}

func TestDiffIsEmptyWhenSnapshotMatches(t *testing.T) {
	handle := newTestDB(t)
	desired := migrate.SnapshotOf([]*model.Schema{schemaFor(t, handle, widget{})})
	if change := migrate.Diff(desired, desired); !change.Empty() {
		t.Errorf("expected no changes, got %d", len(change.Ops))
	}
}

func TestDiffDetectsAddedColumn(t *testing.T) {
	handle := newTestDB(t)
	before := migrate.SnapshotOf([]*model.Schema{schemaFor(t, handle, widget{})})
	after := migrate.SnapshotOf([]*model.Schema{schemaFor(t, handle, widgetV2{})})

	change := migrate.Diff(before, after)
	if len(change.Ops) != 1 {
		t.Fatalf("ops = %d, want 1", len(change.Ops))
	}
	added, ok := change.Ops[0].(migrate.AddColumn)
	if !ok {
		t.Fatalf("op = %T, want AddColumn", change.Ops[0])
	}
	if added.Table != "widgets" || added.Column.Name != "quantity" {
		t.Errorf("unexpected op: %+v", added)
	}
}

func TestDiffWarnsAboutPossibleRenameAndDrops(t *testing.T) {
	before := migrate.Snapshot{Tables: []migrate.Table{{
		Name: "widgets",
		Columns: []migrate.Column{
			{Name: "id", Kind: migrate.KindString, PrimaryKey: true},
			{Name: "title", Kind: migrate.KindString},
		},
	}}}
	after := migrate.Snapshot{Tables: []migrate.Table{{
		Name: "widgets",
		Columns: []migrate.Column{
			{Name: "id", Kind: migrate.KindString, PrimaryKey: true},
			{Name: "name", Kind: migrate.KindString},
		},
	}}}

	change := migrate.Diff(before, after)
	joined := strings.Join(change.Warnings, " ")
	if !strings.Contains(joined, "RenameColumn") {
		t.Errorf("expected a rename hint, got %v", change.Warnings)
	}

	dropped := migrate.Diff(before, migrate.Snapshot{})
	if len(dropped.Ops) != 1 {
		t.Fatalf("ops = %d, want 1", len(dropped.Ops))
	}
	if _, ok := dropped.Ops[0].(migrate.DropTable); !ok {
		t.Errorf("op = %T, want DropTable", dropped.Ops[0])
	}
	if !strings.Contains(strings.Join(dropped.Warnings, " "), "destroy its data") {
		t.Error("dropping a table should warn about data loss")
	}
}

func TestGeneratedFileIsValidGoAndCarriesComments(t *testing.T) {
	handle := newTestDB(t)
	dir := t.TempDir()
	desired := migrate.SnapshotOf([]*model.Schema{schemaFor(t, handle, widget{})})

	generated, err := migrate.Generate(dir, "create widgets", migrate.Diff(migrate.Snapshot{}, desired))
	if err != nil {
		t.Fatal(err)
	}
	if filepath.Base(generated.Path) != "0001_create_widgets.go" {
		t.Errorf("path = %q", generated.Path)
	}

	raw, err := os.ReadFile(generated.Path)
	if err != nil {
		t.Fatal(err)
	}
	source := string(raw)
	for _, want := range []string{
		"package migrations",
		"// Generated by: coyote makemigrations",
		"migrate.Register(migrate.Migration{",
		`ID: "0001_create_widgets"`,
		"// create table widgets",
		"migrate.CreateTable{",
		"model.KindString",
	} {
		if !strings.Contains(source, want) {
			t.Errorf("generated file missing %q:\n%s", want, source)
		}
	}

	next, err := migrate.NextSequence(dir)
	if err != nil {
		t.Fatal(err)
	}
	if next != 2 {
		t.Errorf("next sequence = %d, want 2", next)
	}
}

func TestSnapshotRoundTrip(t *testing.T) {
	handle := newTestDB(t)
	dir := t.TempDir()
	desired := migrate.SnapshotOf([]*model.Schema{schemaFor(t, handle, widget{})})

	if err := migrate.SaveSnapshot(dir, desired); err != nil {
		t.Fatal(err)
	}
	loaded, err := migrate.LoadSnapshot(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(loaded.Tables) != 1 || loaded.Tables[0].Name != "widgets" {
		t.Fatalf("loaded = %+v", loaded)
	}
	if change := migrate.Diff(loaded, desired); !change.Empty() {
		t.Errorf("a round tripped snapshot should diff clean, got %d ops", len(change.Ops))
	}

	missing, err := migrate.LoadSnapshot(t.TempDir())
	if err != nil {
		t.Errorf("a missing snapshot should not be an error: %v", err)
	}
	if len(missing.Tables) != 0 {
		t.Error("a missing snapshot should be empty")
	}
}

func TestRunnerAppliesAndRecordsOnce(t *testing.T) {
	handle := newTestDB(t)
	ctx := context.Background()
	schema := schemaFor(t, handle, widget{})
	change := migrate.Diff(migrate.Snapshot{}, migrate.SnapshotOf([]*model.Schema{schema}))

	first := migrate.Migration{ID: "0001_create_widgets", Up: change.Ops}
	runner := migrate.NewRunner(handle, settings.SQLite, []migrate.Migration{first})

	if err := runner.Prepare(ctx); err != nil {
		t.Fatal(err)
	}
	pending, err := runner.Pending(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if len(pending) != 1 {
		t.Fatalf("pending = %d, want 1", len(pending))
	}
	if err := runner.Apply(ctx, first); err != nil {
		t.Fatal(err)
	}
	if !handle.Migrator().HasTable("widgets") {
		t.Error("table was not created")
	}

	pending, err = runner.Pending(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if len(pending) != 0 {
		t.Errorf("pending after apply = %d, want 0", len(pending))
	}

	applied, err := runner.Applied(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if len(applied) != 1 || applied[0].ID != "0001_create_widgets" {
		t.Fatalf("ledger = %+v", applied)
	}
	if applied[0].Checksum == "" {
		t.Error("the ledger should record a checksum")
	}
}

func TestRunnerRejectsEditedMigration(t *testing.T) {
	handle := newTestDB(t)
	ctx := context.Background()
	schema := schemaFor(t, handle, widget{})
	ops := migrate.Diff(migrate.Snapshot{}, migrate.SnapshotOf([]*model.Schema{schema})).Ops

	original := migrate.Migration{ID: "0001_create_widgets", Up: ops}
	runner := migrate.NewRunner(handle, settings.SQLite, []migrate.Migration{original})
	if err := runner.Prepare(ctx); err != nil {
		t.Fatal(err)
	}
	if err := runner.Apply(ctx, original); err != nil {
		t.Fatal(err)
	}

	edited := migrate.Migration{ID: "0001_create_widgets", Up: append(ops,
		migrate.AddColumn{Table: "widgets", Column: migrate.Column{Name: "sneaky", Kind: migrate.KindString}})}
	tampered := migrate.NewRunner(handle, settings.SQLite, []migrate.Migration{edited})

	if _, err := tampered.Pending(ctx); !errors.Is(err, migrate.ErrChecksumMismatch) {
		t.Errorf("got %v, want ErrChecksumMismatch", err)
	}
}

func TestRunnerRollsBackAFailedMigration(t *testing.T) {
	handle := newTestDB(t)
	ctx := context.Background()

	broken := migrate.Migration{ID: "0001_broken", Up: []migrate.Op{
		migrate.CreateTable{Table: migrate.Table{
			Name:    "good",
			Columns: []migrate.Column{{Name: "id", Kind: migrate.KindString, PrimaryKey: true}},
		}},
		migrate.RunSQL{Any: "THIS IS NOT SQL"},
	}}
	runner := migrate.NewRunner(handle, settings.SQLite, []migrate.Migration{broken})
	if err := runner.Prepare(ctx); err != nil {
		t.Fatal(err)
	}
	if err := runner.Apply(ctx, broken); err == nil {
		t.Fatal("expected the migration to fail")
	}
	if handle.Migrator().HasTable("good") {
		t.Error("a failed migration must roll back the whole transaction")
	}
	applied, _ := runner.Applied(ctx)
	if len(applied) != 0 {
		t.Error("a failed migration must not be recorded")
	}
}

func TestDataMigrationRunsGoCode(t *testing.T) {
	handle := newTestDB(t)
	ctx := context.Background()
	schema := schemaFor(t, handle, widget{})
	create := migrate.Diff(migrate.Snapshot{}, migrate.SnapshotOf([]*model.Schema{schema})).Ops

	backfilled := false
	migrations := []migrate.Migration{
		{ID: "0001_create_widgets", Up: create},
		{ID: "0002_backfill", Note: "seed a widget", Up: []migrate.Op{
			migrate.RunGo{Note: "seed", Func: func(ctx context.Context, tx *gorm.DB) error {
				backfilled = true
				return tx.Table("widgets").Create(map[string]any{"id": "w1", "label": "Seeded"}).Error
			}},
		}},
	}

	runner := migrate.NewRunner(handle, settings.SQLite, migrations)
	if err := runner.Prepare(ctx); err != nil {
		t.Fatal(err)
	}
	pending, err := runner.Pending(ctx)
	if err != nil {
		t.Fatal(err)
	}
	for _, m := range pending {
		if err := runner.Apply(ctx, m); err != nil {
			t.Fatalf("%s: %v", m.ID, err)
		}
	}
	if !backfilled {
		t.Error("the data migration did not run")
	}

	var count int64
	handle.Table("widgets").Count(&count)
	if count != 1 {
		t.Errorf("rows = %d, want 1", count)
	}

	pending, _ = runner.Pending(ctx)
	if len(pending) != 0 {
		t.Error("a data migration must not run twice")
	}
}

func TestSQLRenderingPerDialect(t *testing.T) {
	table := migrate.Table{
		Name: "widgets",
		Columns: []migrate.Column{
			{Name: "id", Kind: migrate.KindString, Size: 64, PrimaryKey: true, NotNull: true},
			{Name: "label", Kind: migrate.KindString, Size: 120, NotNull: true},
			{Name: "price", Kind: migrate.KindFloat},
			{Name: "made_at", Kind: migrate.KindTime},
		},
	}
	op := migrate.CreateTable{Table: table}

	for _, c := range []struct {
		engine settings.Engine
		want   []string
	}{
		{settings.SQLite, []string{`"widgets"`, "TEXT", "REAL", "DATETIME"}},
		{settings.Postgres, []string{`"widgets"`, "VARCHAR(64)", "DOUBLE PRECISION", "TIMESTAMPTZ"}},
		{settings.MySQL, []string{"`widgets`", "VARCHAR(120)", "DOUBLE", "DATETIME"}},
	} {
		statements := op.Statements(dialect.For(c.engine))
		joined := strings.Join(statements, "\n")
		for _, want := range c.want {
			if !strings.Contains(joined, want) {
				t.Errorf("%s SQL missing %q:\n%s", c.engine, want, joined)
			}
		}
	}
}

func TestRegistryOrdersAndRejectsDuplicates(t *testing.T) {
	registry := migrate.NewRegistry()
	if err := registry.Add(
		migrate.Migration{ID: "0002_second"},
		migrate.Migration{ID: "0001_first"},
	); err != nil {
		t.Fatal(err)
	}
	all := registry.All()
	if len(all) != 2 || all[0].ID != "0001_first" {
		t.Fatalf("registry order = %+v", all)
	}
	if err := registry.Add(migrate.Migration{ID: "0001_first"}); err == nil {
		t.Error("duplicate ids should be rejected")
	}
	if err := registry.Add(migrate.Migration{}); err == nil {
		t.Error("a migration without an ID should be rejected")
	}
}

func TestGeneratedMigrationsTypeCheck(t *testing.T) {
	handle := newTestDB(t)
	dir := t.TempDir()

	before := migrate.SnapshotOf([]*model.Schema{schemaFor(t, handle, widget{})})
	generated, err := migrate.Generate(dir, "create widgets", migrate.Diff(migrate.Snapshot{}, before))
	if err != nil {
		t.Fatal(err)
	}

	after := migrate.SnapshotOf([]*model.Schema{schemaFor(t, handle, widgetV2{})})
	change := migrate.Diff(before, after)
	if change.Empty() {
		t.Fatal("adding a column should produce a change")
	}
	second, err := migrate.Generate(dir, "add quantity", change)
	if err != nil {
		t.Fatal(err)
	}

	for _, path := range []string{generated.Path, second.Path} {
		raw, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		for _, literal := range []string{"Column: {", "Columns: {", "Index: {"} {
			if strings.Contains(string(raw), literal) {
				t.Errorf("%s emits an untyped composite literal %q; it will not compile:\n%s",
					filepath.Base(path), literal, raw)
			}
		}
	}

	raw, err := os.ReadFile(second.Path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(raw), "Column: migrate.Column{") {
		t.Errorf("a standalone column needs its type name:\n%s", raw)
	}
}

func TestCompositePrimaryKeysAreDeclaredOnce(t *testing.T) {
	columns := []dialect.Column{
		{Name: "role_id", Type: "text", NotNull: true, PrimaryKey: true},
		{Name: "permission_id", Type: "text", NotNull: true, PrimaryKey: true},
	}

	for _, d := range []dialect.Dialect{dialect.SQLite{}, dialect.Postgres{}, dialect.MySQL{}} {
		sql := d.CreateTable("role_permissions", columns)
		if strings.Count(sql, "PRIMARY KEY") != 1 {
			t.Errorf("%T: a composite key must be declared once:\n%s", d, sql)
		}
		if !strings.Contains(sql, "PRIMARY KEY (") {
			t.Errorf("%T: expected a table-level key:\n%s", d, sql)
		}
	}
}

func TestSingleColumnKeysStayInlineOnSQLite(t *testing.T) {
	sql := dialect.SQLite{}.CreateTable("widgets", []dialect.Column{
		{Name: "id", Type: "integer", NotNull: true, PrimaryKey: true, AutoIncrement: true},
		{Name: "label", Type: "text", NotNull: true},
	})
	if !strings.Contains(sql, `"id" integer PRIMARY KEY`) {
		t.Errorf("a single key should stay inline so sqlite treats it as the rowid:\n%s", sql)
	}
	if strings.Contains(sql, "PRIMARY KEY (") {
		t.Errorf("a single key should not be repeated at table level:\n%s", sql)
	}
}

type widgetWiderLabel struct {
	ID       string `gorm:"primaryKey;size:64"`
	Label    string `gorm:"not null;size:200"`
	Quantity int
}

func (widgetWiderLabel) TableName() string { return "widgets" }

func TestGeneratedMigrationsImportEverythingTheyReference(t *testing.T) {
	handle := newTestDB(t)
	dir := t.TempDir()

	const modelImport = `"github.com/farhapartex/coyote/core/model"`

	base := migrate.SnapshotOf([]*model.Schema{schemaFor(t, handle, widget{})})
	withColumn := migrate.SnapshotOf([]*model.Schema{schemaFor(t, handle, widgetV2{})})
	withWiderColumn := migrate.SnapshotOf([]*model.Schema{schemaFor(t, handle, widgetWiderLabel{})})

	steps := []struct {
		name   string
		change migrate.Change
	}{
		{"create widgets", migrate.Diff(migrate.Snapshot{}, base)},
		{"add quantity", migrate.Diff(base, withColumn)},
		{"widen label", migrate.Diff(withColumn, withWiderColumn)},
		{"drop widgets", migrate.Diff(withWiderColumn, migrate.Snapshot{})},
	}

	for _, step := range steps {
		if step.change.Empty() {
			t.Fatalf("%s should produce a change", step.name)
		}

		generated, err := migrate.Generate(dir, step.name, step.change)
		if err != nil {
			t.Fatalf("%s: %v", step.name, err)
		}

		raw, err := os.ReadFile(generated.Path)
		if err != nil {
			t.Fatal(err)
		}
		source := string(raw)

		uses := strings.Contains(source, "model.")
		imports := strings.Contains(source, modelImport)

		if uses && !imports {
			t.Errorf("%s references model.* but does not import core/model, so it will not compile:\n%s",
				step.name, source)
		}
		if !uses && imports {
			t.Errorf("%s imports core/model without using it, which is a compile error:\n%s",
				step.name, source)
		}
	}
}

func TestAnAlteredColumnGeneratesACompilableMigration(t *testing.T) {
	handle := newTestDB(t)
	dir := t.TempDir()

	before := migrate.SnapshotOf([]*model.Schema{schemaFor(t, handle, widgetV2{})})
	after := migrate.SnapshotOf([]*model.Schema{schemaFor(t, handle, widgetWiderLabel{})})

	change := migrate.Diff(before, after)
	if change.Empty() {
		t.Fatal("widening a column should produce a change")
	}

	generated, err := migrate.Generate(dir, "widen label", change)
	if err != nil {
		t.Fatal(err)
	}

	raw, err := os.ReadFile(generated.Path)
	if err != nil {
		t.Fatal(err)
	}
	source := string(raw)

	if !strings.Contains(source, "migrate.AlterColumn{") {
		t.Fatalf("expected an AlterColumn op:\n%s", source)
	}
	if !strings.Contains(source, `"github.com/farhapartex/coyote/core/model"`) {
		t.Errorf("an AlterColumn migration needs the model import for its Kind constants:\n%s", source)
	}
}

type widgetIndexedLabel struct {
	ID    string `gorm:"primaryKey;size:64"`
	Label string `gorm:"not null;size:120;index"`
}

func (widgetIndexedLabel) TableName() string { return "widgets" }

type widgetUniqueLabel struct {
	ID    string `gorm:"primaryKey;size:64"`
	Label string `gorm:"not null;size:120;uniqueIndex"`
}

func (widgetUniqueLabel) TableName() string { return "widgets" }

func TestMakingAnIndexUniqueIsDetected(t *testing.T) {
	handle := newTestDB(t)

	indexed := migrate.SnapshotOf([]*model.Schema{schemaFor(t, handle, widgetIndexedLabel{})})
	unique := migrate.SnapshotOf([]*model.Schema{schemaFor(t, handle, widgetUniqueLabel{})})

	change := migrate.Diff(indexed, unique)
	if change.Empty() {
		t.Fatal("changing an index to unique must produce a change; the index keeps its name, " +
			"so comparing names alone would miss it")
	}

	var dropped, created int
	var createdUnique bool
	for _, op := range change.Ops {
		switch typed := op.(type) {
		case migrate.DropIndex:
			dropped++
		case migrate.CreateIndex:
			created++
			createdUnique = typed.Unique
		}
	}

	if dropped != 1 || created != 1 {
		t.Errorf("expected the index to be dropped and recreated, got %d drops and %d creates",
			dropped, created)
	}
	if !createdUnique {
		t.Error("the recreated index should be unique")
	}

	if _, isDrop := change.Ops[0].(migrate.DropIndex); !isDrop {
		t.Errorf("the drop must come first, got %T", change.Ops[0])
	}
}

func TestMakingAnIndexNonUniqueIsDetected(t *testing.T) {
	handle := newTestDB(t)

	unique := migrate.SnapshotOf([]*model.Schema{schemaFor(t, handle, widgetUniqueLabel{})})
	indexed := migrate.SnapshotOf([]*model.Schema{schemaFor(t, handle, widgetIndexedLabel{})})

	change := migrate.Diff(unique, indexed)
	if change.Empty() {
		t.Fatal("relaxing a unique index must produce a change")
	}

	for _, op := range change.Ops {
		if created, ok := op.(migrate.CreateIndex); ok && created.Unique {
			t.Error("the recreated index should no longer be unique")
		}
	}
}

func TestAnUnchangedIndexProducesNothing(t *testing.T) {
	handle := newTestDB(t)

	first := migrate.SnapshotOf([]*model.Schema{schemaFor(t, handle, widgetUniqueLabel{})})
	second := migrate.SnapshotOf([]*model.Schema{schemaFor(t, handle, widgetUniqueLabel{})})

	if change := migrate.Diff(first, second); !change.Empty() {
		t.Errorf("an unchanged schema must not churn migrations, got %d op(s)", len(change.Ops))
	}
}

func TestSQLiteNeedsNoAdvisoryLockToMigrate(t *testing.T) {
	handle := newTestDB(t)
	runner := migrate.NewRunner(handle, settings.SQLite, nil)

	ran := false
	if err := runner.WithLock(t.Context(), func() error {
		ran = true
		return nil
	}); err != nil {
		t.Fatalf("WithLock: %v", err)
	}
	if !ran {
		t.Error("the body should still run on an engine with no advisory lock")
	}
}

func TestWithLockCarriesTheBodysError(t *testing.T) {
	handle := newTestDB(t)
	runner := migrate.NewRunner(handle, settings.SQLite, nil)

	want := errors.New("the migration failed")
	if err := runner.WithLock(t.Context(), func() error { return want }); !errors.Is(err, want) {
		t.Errorf("error = %v, want the body's own error", err)
	}
}

func TestEnginesReportWhetherTheirDDLIsTransactional(t *testing.T) {
	for engine, want := range map[settings.Engine]bool{
		settings.SQLite:   true,
		settings.Postgres: true,
		settings.MySQL:    false,
	} {
		runner := migrate.NewRunner(newTestDB(t), engine, nil)
		if got := runner.TransactionalDDL(); got != want {
			t.Errorf("%s TransactionalDDL = %v, want %v", engine, got, want)
		}
	}
}

func TestQuotingLeavesExactlyOneIdentifier(t *testing.T) {
	cases := []struct {
		d       dialect.Dialect
		quote   string
		hostile string
	}{
		{dialect.SQLite{}, `"`, `t"; DROP TABLE users; --`},
		{dialect.Postgres{}, `"`, `t"; DROP TABLE users; --`},
		{dialect.MySQL{}, "`", "t`; DROP TABLE users; --"},
	}
	for _, c := range cases {
		quoted := c.d.Quote(c.hostile)
		bare := strings.ReplaceAll(quoted, c.quote+c.quote, "")
		if got := strings.Count(bare, c.quote); got != 2 {
			t.Errorf("%s quoted %q with %d unescaped delimiters, want 2", c.d.Name(), quoted, got)
		}
	}
}

func TestAHostileTableNameCannotDropAnotherTable(t *testing.T) {
	handle := newTestDB(t)
	if err := handle.Exec(`CREATE TABLE users (id TEXT)`).Error; err != nil {
		t.Fatal(err)
	}

	hostile := `t"; DROP TABLE users; --`
	create := dialect.SQLite{}.CreateTable(hostile, []dialect.Column{
		{Name: "id", Type: "TEXT", PrimaryKey: true},
	})
	if err := handle.Exec(create).Error; err != nil {
		t.Fatalf("the quoted identifier should be legal SQL: %v\n%s", err, create)
	}

	if !handle.Migrator().HasTable("users") {
		t.Error("users was dropped by a table name")
	}
	if !handle.Migrator().HasTable(hostile) {
		t.Errorf("the table should exist under its literal name")
	}
}
