package migrations

// Generated by: go tool coyote makemigrations
// Edit freely before applying — this file is the source of truth once committed.

import (
	"github.com/farhapartex/coyote/core/model"

	"github.com/farhapartex/coyote/contrib/migrate"
)

func init() {
	migrate.Register(migrate.Migration{
		ID: "0001_initial",
		Up: []migrate.Op{
			// create table checkouts
			migrate.CreateTable{Table: migrate.Table{
				Name: "checkouts",
				Columns: []migrate.Column{
					{Name: "id", Kind: model.KindString, Size: 64, NotNull: true, PrimaryKey: true},
					{Name: "reference", Kind: model.KindString, Size: 64, NotNull: true},
					{Name: "total", Kind: model.KindFloat, Size: 64},
					{Name: "paid_at", Kind: model.KindTime},
					{Name: "created_at", Kind: model.KindTime},
					{Name: "updated_at", Kind: model.KindTime},
				},
				Indexes: []migrate.Index{
					{Name: "idx_checkouts_reference", Columns: []string{"reference"}, Unique: true},
				},
			}},
			// create table products
			migrate.CreateTable{Table: migrate.Table{
				Name: "products",
				Columns: []migrate.Column{
					{Name: "id", Kind: model.KindString, Size: 64, NotNull: true, PrimaryKey: true},
					{Name: "name", Kind: model.KindString, Size: 200, NotNull: true},
					{Name: "sku", Kind: model.KindString, Size: 64, NotNull: true},
					{Name: "price", Kind: model.KindFloat, Size: 64},
					{Name: "stock", Kind: model.KindInt, Size: 64},
					{Name: "description", Kind: model.KindText, Size: 2000},
					{Name: "is_published", Kind: model.KindBool},
					{Name: "created_at", Kind: model.KindTime},
					{Name: "updated_at", Kind: model.KindTime},
				},
				Indexes: []migrate.Index{
					{Name: "idx_products_is_published", Columns: []string{"is_published"}, Unique: false},
					{Name: "idx_products_sku", Columns: []string{"sku"}, Unique: true},
				},
			}},
			// create table users
			migrate.CreateTable{Table: migrate.Table{
				Name: "users",
				Columns: []migrate.Column{
					{Name: "id", Kind: model.KindString, Size: 64, NotNull: true, PrimaryKey: true},
					{Name: "first_name", Kind: model.KindString},
					{Name: "last_name", Kind: model.KindString},
					{Name: "email", Kind: model.KindString, Size: 320},
					{Name: "username", Kind: model.KindString, Size: 64, NotNull: true},
					{Name: "password", Kind: model.KindString, NotNull: true},
					{Name: "is_active", Kind: model.KindBool, Default: "true"},
					{Name: "is_superadmin", Kind: model.KindBool},
					{Name: "last_login_at", Kind: model.KindTime},
					{Name: "created_at", Kind: model.KindTime},
					{Name: "updated_at", Kind: model.KindTime},
				},
				Indexes: []migrate.Index{
					{Name: "idx_users_email", Columns: []string{"email"}, Unique: false},
					{Name: "idx_users_is_active", Columns: []string{"is_active"}, Unique: false},
					{Name: "idx_users_is_superadmin", Columns: []string{"is_superadmin"}, Unique: false},
					{Name: "idx_users_username", Columns: []string{"username"}, Unique: true},
				},
			}},
		},
	})
}
