package migrations

// Generated by: coyote makemigrations
// Edit freely before applying — this file is the source of truth once committed.

import (
	"github.com/farhapartex/coyote/core/model"

	"github.com/farhapartex/coyote/contrib/migrate"
)

func init() {
	migrate.Register(migrate.Migration{
		ID: "0002_staff_and_permissions",
		Up: []migrate.Op{
			// create table permissions
			migrate.CreateTable{Table: migrate.Table{
				Name: "permissions",
				Columns: []migrate.Column{
					{Name: "id", Kind: model.KindString, Size: 64, NotNull: true, PrimaryKey: true},
					{Name: "resource", Kind: model.KindString, Size: 100, NotNull: true},
					{Name: "action", Kind: model.KindString, Size: 20, NotNull: true},
					{Name: "label", Kind: model.KindString, Size: 150},
					{Name: "created_at", Kind: model.KindTime},
				},
				Indexes: []migrate.Index{
					{Name: "idx_permission_codename", Columns: []string{"resource", "action"}, Unique: true},
				},
			}},
			// create table role_permissions
			migrate.CreateTable{Table: migrate.Table{
				Name: "role_permissions",
				Columns: []migrate.Column{
					{Name: "role_id", Kind: model.KindString, Size: 64, NotNull: true, PrimaryKey: true},
					{Name: "permission_id", Kind: model.KindString, Size: 64, NotNull: true, PrimaryKey: true},
				},
			}},
			// create table roles
			migrate.CreateTable{Table: migrate.Table{
				Name: "roles",
				Columns: []migrate.Column{
					{Name: "id", Kind: model.KindString, Size: 64, NotNull: true, PrimaryKey: true},
					{Name: "name", Kind: model.KindString, Size: 100, NotNull: true},
					{Name: "description", Kind: model.KindString, Size: 255},
					{Name: "created_at", Kind: model.KindTime},
					{Name: "updated_at", Kind: model.KindTime},
				},
				Indexes: []migrate.Index{
					{Name: "idx_roles_name", Columns: []string{"name"}, Unique: true},
				},
			}},
			// create table user_roles
			migrate.CreateTable{Table: migrate.Table{
				Name: "user_roles",
				Columns: []migrate.Column{
					{Name: "user_id", Kind: model.KindString, Size: 64, NotNull: true, PrimaryKey: true},
					{Name: "role_id", Kind: model.KindString, Size: 64, NotNull: true, PrimaryKey: true},
				},
			}},
			// add column users.is_staff
			migrate.AddColumn{Table: "users", Column: migrate.Column{Name: "is_staff", Kind: model.KindBool}},
			// create index idx_users_is_staff on users
			migrate.CreateIndex{Table: "users", Name: "idx_users_is_staff", Columns: []string{"is_staff"}, Unique: false},
		},
	})
}
