package migrations

// Generated by: coyote makemigrations
// Edit freely before applying — this file is the source of truth once committed.

import (
	"github.com/farhapartex/coyote/core/model"

	"github.com/farhapartex/coyote/contrib/migrate"
)

func init() {
	migrate.Register(migrate.Migration{
		ID: "0003_product_photo",
		Up: []migrate.Op{
			// add column products.photo
			migrate.AddColumn{Table: "products", Column: migrate.Column{Name: "photo", Kind: model.KindString, Size: 200}},
		},
	})
}
