package migrate

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/farhapartex/coyote/lib/text"
)

const generatedPackage = "migrations"

var fileNamePattern = regexp.MustCompile(`^(\d{4})_[a-z0-9_]+\.go$`)

type Generated struct {
	ID       string
	Path     string
	Warnings []string
}

func NextSequence(dir string) (int, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return 1, nil
		}
		return 0, fmt.Errorf("coyote/migrate: reading %s: %w", dir, err)
	}
	highest := 0
	for _, entry := range entries {
		match := fileNamePattern.FindStringSubmatch(entry.Name())
		if match == nil {
			continue
		}
		number := 0
		fmt.Sscanf(match[1], "%d", &number)
		if number > highest {
			highest = number
		}
	}
	return highest + 1, nil
}

func slugFor(name string) string {
	if slug := text.Slugify(name); slug != "" {
		return slug
	}
	return "auto"
}

func Generate(dir, name string, change Change) (Generated, error) {
	sequence, err := NextSequence(dir)
	if err != nil {
		return Generated{}, err
	}
	slug := slugFor(name)
	id := fmt.Sprintf("%04d_%s", sequence, slug)
	path := filepath.Join(dir, id+".go")

	if err := os.MkdirAll(dir, 0o755); err != nil {
		return Generated{}, fmt.Errorf("coyote/migrate: creating %s: %w", dir, err)
	}
	if err := os.WriteFile(path, []byte(render(id, change)), 0o644); err != nil {
		return Generated{}, fmt.Errorf("coyote/migrate: writing %s: %w", path, err)
	}
	return Generated{ID: id, Path: path, Warnings: change.Warnings}, nil
}

func render(id string, change Change) string {
	var b strings.Builder

	fmt.Fprintf(&b, "package %s\n\n", generatedPackage)
	b.WriteString("// Generated by: coyote makemigrations\n")
	b.WriteString("// Edit freely before applying — this file is the source of truth once committed.\n")
	if len(change.Warnings) > 0 {
		b.WriteString("//\n// Review before applying:\n")
		for _, warning := range change.Warnings {
			fmt.Fprintf(&b, "//   - %s\n", warning)
		}
	}
	b.WriteString("\nimport (\n")
	if usesModelPackage(change.Ops) {
		b.WriteString("\t\"github.com/farhapartex/coyote/core/model\"\n\n")
	}
	b.WriteString("\t\"github.com/farhapartex/coyote/contrib/migrate\"\n)\n\n")

	b.WriteString("func init() {\n")
	b.WriteString("\tmigrate.Register(migrate.Migration{\n")
	fmt.Fprintf(&b, "\t\tID: %q,\n", id)
	b.WriteString("\t\tUp: []migrate.Op{\n")
	for _, op := range change.Ops {
		source, ok := op.(Sourcer)
		if !ok {
			continue
		}
		fmt.Fprintf(&b, "\t\t\t// %s\n", op.Describe())
		fmt.Fprintf(&b, "\t\t\t%s,\n", source.Source())
	}
	b.WriteString("\t\t},\n\t})\n}\n")
	return b.String()
}

func usesModelPackage(ops []Op) bool {
	for _, op := range ops {
		switch op.(type) {
		case CreateTable, AddColumn:
			return true
		}
	}
	return false
}

func SortedTables(tables []Table) []Table {
	out := append([]Table{}, tables...)
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}
